name: the_alarm_clock
description: A Flutter alarm clock with world clock, stopwatch, and timer.
publish_to: 'none'
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  provider: ^6.0.0
  sqflite: ^2.3.0
  path: ^1.8.0
  json_annotation: ^4.8.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  build_runner: ^2.4.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
